### ISSUE TITLE
[low priority] cannot disassemble some fencing objects

### ISSUE THREAD

**Issue by user2345679** [eI1on/pz-building-menu#20]
Unsure if this is due to engine limitations but the following objects are unable to be 'disassembled' by the player.
fencing > other > (all)
fencing > railing > (all)
-----
This is a low priority issue due to some multiplayer servers not allowing players to use the 'destroy' feature.
note: there may be more objects like this, if so I will update this post in the future.

**Comment by eI1on** [comment]
The inability to "disassemble" certain objects is currently by design, to maintain game balance and prevent unintentional object destruction, especially in multiplayer settings. Changing the Flags property to allow disassembly of objects could result in easier and potentially disruptive destruction of objects. I've added "disassembly" for the fencing objects mentioned and will cautiously consider other extensions.

**Comment by user2345679** [comment]
> The inability to "disassemble" certain objects is currently by design
Ah I understand. I am new to the game and I can see why you have it set that way -- considering this report solved/closed
p.s. thanks for the mod, enjoying it.

**Comment by user2345679** [comment]
Ah I understand. I am new to the game and I can see why you have it set that way -- considering this report solved/closed
p.s. thanks for the mod, enjoying it.

**Comment by user2345679** [comment]
Ah I understand. I am new to the game and I can see why you have it set that way -- considering this report solved/closed
p.s. thanks for the mod, enjoying it.
