### ISSUE TITLE
Some tiles not able to be selected. no other building mods.

### ISSUE THREAD

**Issue by Teddybear1848** [eI1on/pz-building-menu#25]
On my (linux) dedicated server, players can not use some of the tiles, mostly metal fences and 3 to 4 tile garage doors. Ive tried un subbing and re subbing multiple times. No errors are thrown. 

https://github.com/eI1on/pz-building-menu/assets/161921511/5f0b9a95-8820-4d99-8b15-debf2bbf6640

**Comment by Teddybear1848** [comment]
[02-03-24_01-15-05_DebugLog-server.txt](https://github.com/eI1on/pz-building-menu/files/14468343/02-03-24_01-15-05_DebugLog-server.txt)

**Comment by Teddybear1848** [comment]
https://github.com/eI1on/pz-building-menu/assets/161921511/47b9fa9a-7796-42e9-b4ba-27875d2cead2

**Comment by eI1on** [comment]
Thanks, I managed to find out why you couldn't build with the Build Cheat toggled. I'll update the mod in a few hours.
Fixed with this commit [7197ee4](https://github.com/eI1on/pz-building-menu/commit/7197ee44450050b3dc062fd9c98a45b87624b450#diff-8909881ac3276a905ba155218056b6e55c4fa06739c1b643a01b66ee46b6d7a3R80)

**Comment by Teddybear1848** [comment]
Thank you very much for your help and fast responses!
