### ISSUE TITLE
Locked garage doors can be pry'ed open on mp server

### ISSUE THREAD

**Issue by user2345679** [eI1on/pz-building-menu#29]
On the SeriousSurvivalRP server they use your mod and 2 additional ones:
- 'common sense' (allows pry)
- 'Door Padlocks' (allows you to put crafted lock onto player built door so that it uses a key and isnt able to be pry'ed)

All door types except for Garage Door types in your mod work properly (if the 'door padlock' is applied they cannot be pryed by players)
Garage doors when padlocked are still able to be pryed open.

-----
Semi related issue that may be helpful: garage doors that are not padlocked, if you go behind them and right click them they behave as if you have a key to the door.

**Comment by user2345679** [comment]
update: I edited the OP to be more concise and wanted to replace the video with something faster to watch that displays all cases

https://github.com/eI1on/pz-building-menu/assets/160158836/d98a3a23-e491-43f8-bce3-d55fb29d7e84

**Comment by eI1on** [comment]
The problem is that BB CommonSense does not check if the garage has a lock set by the player, because this option is not vanilla. It's not really a problem because that's what the mod is supposed to do, open locked doors, not being able to pry open padlocked doors it's just a preference. You have to report it on that mod's page. Specifically they need to add the check for "dlp", or the server administrator in the server patch mod. 
```lua
if instanceof(priableObject, "IsoDoor") 
and priableObject:isLocked() == true 
and priableObject:isBarricaded() == false 
and not priableObject:getModData()["dlp"] then  --- this check in BB_CS_Utils.lua
    context:addOptionOnTop(getText("ContextMenu_Pry_open"), worldobjects, CSUtils.PryEntityOpen, priableObject, playerObj, pryingTool)
    return
end
```
